
services:
  backend:
    build:
      context: ./backend
    container_name: autou-backend
    env_file:
      - ./backend/.env.openApi
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/').read()"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "/api"
    container_name: autou-frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy
